language: python

python:
  - 2.7
  - 3.6

install:
  - pip install poetry
  - poetry install
  - poetry develop

script:
  - poetry run pytest

after_success:
  - pip install coveralls
  - coveralls

deploy:
  provider: pypi
  user: sobolevn
  password: $PYPI_PASSWORD  # password is hidden
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true

notifications:
  email:
    on_success: never
    on_failure: change
